fix: fix stuff

diff --git a/openfaas-functions/fn_speech_recognition/justfile b/openfaas-functions/fn_speech_recognition/justfile
--- a/openfaas-functions/fn_speech_recognition/justfile
+++ b/openfaas-functions/fn_speech_recognition/justfile
@@ -12,12 +12,12 @@ test:
 
 test_all:
     #!/usr/bin/env bash
-    for file in $(ls $PATH_AUDIO/* | head -n 6); do
+    for file in $(ls $PATH_AUDIO/* | head -n 10); do
       echo $file
-      (curl -s --fail-with-body \
+      ((curl -s --fail-with-body \
           -X POST \
           -F "file=@$file"  \
           --output tmp.json \
-          localhost:8081 || echo "Failed for $file")&
+          localhost:8081 && echo "Ok for $file") || echo "Failed for $file")&
     done
     wait
