Avoid checking for uncommited changes in other parts of the project

diff --git a/manager/justfile b/manager/justfile
--- a/manager/justfile
+++ b/manager/justfile
@@ -95,11 +95,12 @@ clean:
 # Check for uncommited changes
 _check_uncommited:
     #!/usr/bin/env bash
-    if [ -n "$(git status --porcelain | grep $PWD))" ]
+    if [ -n "$(git status --porcelain | grep {{invocation_directory()}})" ]
     then
-        echo "ERROR: uncommitted changes"
-        exit 1
+      echo "ERROR: uncommitted changes"
+      exit 1
     fi
+
 # Run market, and two fog nodes as the dev env
 run_dev:
     #!/usr/bin/env bash
