feat: add powerrandom placement algorithm

diff --git a/iot_emulation/justfile b/iot_emulation/justfile
--- a/iot_emulation/justfile
+++ b/iot_emulation/justfile
@@ -16,4 +16,14 @@ update:
     gomod2nix
 
 ghcr user:
-    $(nix build .#iot_emulation --print-out-paths --no-link --quiet) 2> /dev/null | gzip --fast -q | skopeo --insecure-policy copy -q docker-archive:/dev/stdin docker://ghcr.io/{{user}}/giraff:iot_emulation
+    #!/usr/bin/env bash
+    output=`$(nix build .#iot_emulation --print-out-paths --no-link --quiet) 2> /dev/null | gzip --fast -q | skopeo --insecure-policy copy -q docker-archive:/dev/stdin docker://ghcr.io/{{user}}/giraff:iot_emulation 2>&1`
+    retVal=$?
+    if [ $retVal -ne 0 ]; then
+      echo -e "[{{file_name(justfile_directory())}}] upload \033[31mFAILED\033[0m"
+      echo -e $output
+      exit $retVal
+    fi
+    echo -e "[{{file_name(justfile_directory())}}] upload \033[32mOK\033[0m"
+
+
diff --git a/manager/justfile b/manager/justfile
--- a/manager/justfile
+++ b/manager/justfile
@@ -15,8 +15,8 @@ build *FLAGS:
     cargo build {{FLAGS}}
 
 pre_commit:
-    @nix develop .#manager -c just check 
-    @nix develop .#manager -c just check "clippy" 
+    @nix develop .#manager -c just check
+    @nix develop .#manager -c just check "clippy"
     nix develop .#manager -c cargo fmt
 
 # Run cargo check
@@ -31,10 +31,11 @@ check subcommand="check":
     just _{{subcommand}} --features edge_ward
     # just _{{subcommand}} --features edge_ward_v2
     just _{{subcommand}} --features edge_ward_v3
-    
+    just _{{subcommand}} --features powerrandom
+
     just _{{subcommand}} --features jaeger,auction
 
-# Check outdated or unused deps (req. cargo-outdated + updeps crate)
+# Check outdated or unused deps (req. cargo-outdated + updeps create)
 check_deps:
 	cargo outdated -R
 	cargo udeps --all-targets
@@ -57,7 +58,7 @@ run_market *FLAGS:
     cargo run --bin market {{FLAGS}}
 
 # Run the node, type is market or else (generic fog_node)
-run_fog_node node_type MY_IP_ADDRESS debug="false":
+run_fog_node node_type MY_IP_ADDRESS:
     #!.venv/bin/python
     import os
     import base64
@@ -124,10 +125,10 @@ run_fog_node node_type MY_IP_ADDRESS debug="false":
     )'''
 
     if node_type not in nodes:
-        print(f"Wrong node name, select one of the followings: {','.join(nodes.keys())}")
+        print(f"Wrong node name, select one of the following: {','.join(nodes.keys())}")
         exit(1)
     config = nodes[node_type]
-    
+
     env_vars = {}
     env_vars['CONFIG'] = base64.b64encode(bytes(config, "utf-8")).decode("utf-8")
     env_vars['OPENFAAS_USERNAME'] = "admin"
@@ -136,61 +137,59 @@ run_fog_node node_type MY_IP_ADDRESS debug="false":
     env_vars['OPENFAAS_PORT_EXTERNAL'] = "8080"
     env_vars['RUST_LOG'] = "{{RUST_LOG}}"
     env_vars['LOG_CONFIG_FILENAME'] = "{{node_type}}.log"
-    env_vars['COLLECTOR_IP'] = "10.42.0.1"
-    env_vars['OTEL_EXPORTER_OTLP_ENDPOINT_FUNCTION']="http://10.42.0.1:4317" 
+    env_vars['COLLECTOR_IP'] = "127.0.0.1"
+    env_vars['OTEL_EXPORTER_OTLP_ENDPOINT_FUNCTION']="http://10.42.0.1:4317"
 
     env_vars['INFLUX_ADDRESS']="10.42.0.1:9086"
     env_vars['INFLUX_TOKEN']="xowyTh1iGcNAZsZeydESOHKvENvcyPaWg8hUe3tO4vPOw_buZVwOdUrqG3gwV314aYd9SWKHcxlykcQY_rwYVQ=="
     env_vars['INFLUX_ORG']="faasfog"
-    env_vars['INFLUX_BUCKET']="faasfog" 
-    env_vars['INSTANCE_NAME']="{{node_type}}" 
+    env_vars['INFLUX_BUCKET']="faasfog"
+    env_vars['INSTANCE_NAME']="{{node_type}}"
 
-    env_vars['FUNCTION_LIVE_TIMEOUT_MSECS']="120000" 
-    env_vars['PRICING_CPU']="1.0" 
-    env_vars['PRICING_MEM']="1.0" 
-    env_vars['PRICING_CPU_INITIAL']="1.0" 
-    env_vars['PRICING_MEM_INITIAL']="1.0" 
+    env_vars['FUNCTION_LIVE_TIMEOUT_MSECS']="120000"
+    env_vars['PRICING_CPU']="1.0"
+    env_vars['PRICING_MEM']="1.0"
+    env_vars['PRICING_CPU_INITIAL']="1.0"
+    env_vars['PRICING_MEM_INITIAL']="1.0"
     env_vars['PRICING_GEOLOCATION']="1.0"
 
     if "{{node_type}}" in ["node_1", "node_2"]:
         env_vars['IS_CLOUD'] = "is_cloud"
 
-    if "{{debug}}" != "false":
-        env_str = "&".join([f'{key}="{value}"' for key, value in env_vars.items()])
-        cmd = f'code --open-url "vscode://vadimcn.vscode-lldb/launch/command?{env_str}&./target/debug/fog_node"'
-    else:
-        env_str = " ".join([f'{key}="{value}"' for key, value in env_vars.items()])
-        cmd = f'{env_str} ./target/debug/fog_node'
+    env_str = " ".join([f'{key}="{value}"' for key, value in env_vars.items()])
+    cmd = f'{env_str} ./target/debug/fog_node'
 
     print(cmd)
     os.system(cmd)
 
-run MY_IP_ADDRESS debug="false" *FLAGS="--features auction": (build FLAGS)
-    {{ if debug == "false" { "mprocs" } else { "sh -c" } }} "just run_fog_node market {{MY_IP_ADDRESS}} {{debug}}" \
-    {{ if debug == "false" { "" } else { "&& sh -c" } }} "just run_fog_node node_2 {{MY_IP_ADDRESS}} {{debug}}" \
-    {{ if debug == "false" { "" } else { "&& sh -c" } }} "just run_fog_node node_3 {{MY_IP_ADDRESS}} {{debug}}" \
-    {{ if debug == "false" { "" } else { "&& sh -c" } }} "just run_fog_node node_1 {{MY_IP_ADDRESS}} {{debug}}" \
-    {{ if debug == "false" { "" } else { "&& sh -c" } }} "just run_market {{FLAGS}}"
+run MY_IP_ADDRESS *FLAGS="--features auction": (build FLAGS)
+    mprocs "just run_fog_node market {{MY_IP_ADDRESS}}" \
+      "just run_fog_node node_2 {{MY_IP_ADDRESS}}" \
+      "just run_fog_node node_3 {{MY_IP_ADDRESS}}" \
+      "just run_fog_node node_1 {{MY_IP_ADDRESS}}" \
+      "just run_market {{FLAGS}}"
 
 expe localhost_ip $MARKET_LOCAL_PORT=MARKET_PORT IOT_LOCAL_PORT='30080':
     cd ../testbed && nix develop .#testbed -c sh -c 'export EXPE_SAVE_FILE=./requests NODES_IP=127.0.0.1 TARGET_NODE_NAMES=node_3 IOT_LOCAL_PORT={{IOT_LOCAL_PORT}} OVERRIDE_FIRST_NODE_IP=127.0.0.1 OVERRIDE_FUNCTION_IP=127.0.0.1 ; just expe 127.0.0.1 {{localhost_ip}} c132ee95-5368-4bc8-9dfd-227eb77da5fc'
     cd ../testbed && nix develop .#testbed -c sh -c 'export EXPE_LOAD_FILE=./requests NODES_IP=127.0.0.1 TARGET_NODE_NAMES=node_3 IOT_LOCAL_PORT={{IOT_LOCAL_PORT}} OVERRIDE_FIRST_NODE_IP=127.0.0.1 OVERRIDE_FUNCTION_IP=127.0.0.1 ; just expe 127.0.0.1 {{localhost_ip}} c132ee95-5368-4bc8-9dfd-227eb77da5fc'
 
-# Push container images o ghcr.
-ghcr user +images:  
+_ghcr user image:
     #!/usr/bin/env bash
-    set -ex
-    function run_docker() {
-        re="fog_node_(.*)"
-        name=$1
-        if [[ $1 =~ $re  ]]; then
-            name="${BASH_REMATCH[1]}"
-        fi
-        $(nix build ".#$1" --print-out-paths --no-link --quiet) 2> /dev/null | gzip --fast -q | skopeo --insecure-policy copy -q docker-archive:/dev/stdin docker://ghcr.io/{{user}}/giraff:$name
-    }
+    output=`$(nix build ".#{{image}}" --print-out-paths --no-link --quiet) | gzip --fast -q | skopeo --insecure-policy copy -q docker-archive:/dev/stdin docker://ghcr.io/{{user}}/giraff:{{image}} 2>&1`
+    retVal=$?
+    if [ $retVal -ne 0 ]; then
+      echo -e "[{{file_name(justfile_directory())}}] {{image}} \033[31mFAILED\033[0m"
+      echo -e $output
+      exit $retVal
+    fi
+    echo -e "[{{file_name(justfile_directory())}}] {{image}} \033[32mOK\033[0m"
 
-    export -f run_docker
-    parallel --lb --will-cite run_docker ::: {{images}} "market"
+
+# Push container images o ghcr.
+ghcr user +images:
+    #!/usr/bin/env bash
+    set -e
+    parallel --halt-on-error 2 --will-cite just _ghcr {{user}} {1} ::: {{images}}
 
 collect:
     cd ../testbed && nix develop .#testbed -c sh -c 'export SAVE_NETWORK_FILE=/dev/null EXPE_LOAD_FILE=./requests INFLUX_ADDRESS=127.0.0.1:9086; just collect'
diff --git a/openfaas-functions/justfile b/openfaas-functions/justfile
--- a/openfaas-functions/justfile
+++ b/openfaas-functions/justfile
@@ -23,12 +23,20 @@ _ghcr_wrapped user dir:
 _ghcr user dir:
     #!/usr/bin/env bash
     fn_name=$(basename {{dir}})
-    $(nix build .#$fn_name --print-out-paths --no-link --quiet) 2> /dev/null | gzip --fast -q | skopeo --insecure-policy copy -q docker-archive:/dev/stdin docker://ghcr.io/{{user}}/giraff:$fn_name
+    output=`$(nix build .#$fn_name --print-out-paths --no-link --quiet) 2> /dev/null | gzip --fast -q | skopeo --insecure-policy copy -q docker-archive:/dev/stdin docker://ghcr.io/{{user}}/giraff:$fn_name 2>&1`
+    retVal=$?
+    if [ $retVal -ne 0 ]; then
+      echo -e "[{{file_name(justfile_directory())}}] $fn_name \033[31mFAILED\033[0m"
+      echo -e $output
+      exit $retVal
+    fi
+    echo -e "[{{file_name(justfile_directory())}}] $fn_name \033[32mOK\033[0m"
+
 
 _ghcr_all user:
     #!/usr/bin/env bash
     find . -maxdepth 1 -type d -name 'fn_*'  -printf '%f\n' \
-        | parallel --lb just _ghcr_wrapped {{user}} {}
+        | parallel just _ghcr_wrapped {{user}} {}
 
 docker:
     #!/usr/bin/env bash
@@ -38,3 +46,4 @@ docker:
     stream_docker=$(nix build .#$fn_dir  --print-out-paths --no-link --quiet)
     sh -c $stream_docker 2> /dev/null | {{DOCKER}} load
     {{DOCKER}} run --rm --name $fn_dir -p 8081:8080 -e OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true -e OTEL_EXPORTER_OTLP_ENDPOINT_FUNCTION=http://10.42.0.1:4317 -e ID=toto -e NAME=totoname $fn_dir:latest
+
diff --git a/testbed/justfile b/testbed/justfile
--- a/testbed/justfile
+++ b/testbed/justfile
@@ -50,11 +50,39 @@ endpoints:
 
 _is_connected city_name_node_target $market_ip market_port:
     #!/usr/bin/env bash
-    if [[ $(curl -s "$market_ip:{{market_port}}/api/fog" | jq '.[] | select(.tags[] == "{{city_name_node_target}}") | .id' | sed -nE 's/"(.*)"/\1/p') ]]; then
-        echo "✅ {{city_name_node_target}}@$market_ip is connected"
-    else
-        echo "❌ {{city_name_node_target}}@$market_ip"
+    set -o pipefail
+    raw_output=`curl -s "$market_ip:{{market_port}}/api/fog"`
+    output=`echo "$raw_output" | jq '.[] | select(.tags[] == "{{city_name_node_target}}") | .id' | sed -nE 's/"(.*)"/\1/p'`
+    status=$?
+    if [ $status -ne 0 ]; then
+        echo $raw_output
     fi
+    if [ "$output" == "" ]; then
+      echo $raw_output
+      exit 1
+    fi
+    exit $status
+
+_until_is_connected city_name_node_target market_ip market_port:
+    #!/usr/bin/env bash
+    status=1
+    while [ $status -ne 0 ]; do
+      just _is_connected {{city_name_node_target}} {{market_ip}} {{market_port}}
+      status=$?
+      if [ $status -ne 0 ]; then
+        sleep 3
+      fi
+    done
+
+_until_is_connected_timeout city_name_node_target market_ip market_port timeout:
+    #!/usr/bin/env bash
+    output=`timeout {{timeout}} bash -c "just _until_is_connected {{city_name_node_target}} {{market_ip}} {{market_port}}" 2>&1`
+    status=$?
+    if [ $status -ne 0 ]; then
+      echo "Failed to check connection to {{city_name_node_target}} w/ output: $output"
+    fi
+    exit $status
+
 
 [private]
 deploy fog_node_image market_image $DEPLOYMENT_NAME:
@@ -100,14 +128,12 @@ scenario archive_name +city_name_node_targets:
 
     NODE_TARGETS=()
 
-    sleep 60
-
     MARKET_IP=$({{RUN}} integration.py market-ip | grep address | sed 's/address: //')
     # Create bg tasks, push their pid in an array and check after waiting for each when one has failed
     pids=()
+    echo "Checking {{city_name_node_targets}}"
     for city in {{city_name_node_targets}}; do
-        echo "Checking connection to $city"
-        timeout 600 bash -c "until [[ '$(just _is_connected $city $MARKET_IP $MARKET_LOCAL_PORT)' =~ '✅' ]]; do sleep 10 && echo -e '.'; done"&
+        just _until_is_connected_timeout $city $MARKET_IP $MARKET_LOCAL_PORT 300&
         pids+=($!)
     done
 
@@ -117,12 +143,11 @@ scenario archive_name +city_name_node_targets:
       wait "$pid"
       exit_status=$?
       if [ $exit_status -ne 0 ]; then
-        echo "A connection failed to be checked"
         error_occured=1
       fi
     done
     if [ $error_occured -ne 0 ]; then
-      echo "At least one connected failed to be checked failed. Exiting..."
+      echo "At least one connection failed to be checked in time. Exiting..."
       exit 1
     fi
 
@@ -145,8 +170,6 @@ scenario archive_name +city_name_node_targets:
         exit $_status
     fi
     _localstatus=0
-
-    sleep 60
 
     just expe $IOT_IP $MARKET_IP "$joined"
     if (( _localstatus > 0 )); then
@@ -180,15 +203,14 @@ scenarii +city_name_node_targets:
     set -e
 
     function run_scenario() {
-        echo "Using image $IMAGE_REGISTRY/$FOG_NODE_IMAGE_NAME:$2 and $IMAGE_REGISTRY/$MARKET_IMAGE"
+        echo "Using image $IMAGE_REGISTRY/$COMMON_IMAGE_NAME:$2 and $IMAGE_REGISTRY/$COMMON_IMAGE_NAME:$3"
         if [ $1 -eq 1 ]; then
-            just deploy "$IMAGE_REGISTRY/$FOG_NODE_IMAGE_NAME:$2" "$IMAGE_REGISTRY/$MARKET_IMAGE" $DEPLOYMENT_NAME
+            just deploy "$IMAGE_REGISTRY/$COMMON_IMAGE_NAME:$2" "$IMAGE_REGISTRY/$COMMON_IMAGE_NAME:$3" $DEPLOYMENT_NAME
         else
-            just refresh "$IMAGE_REGISTRY/$FOG_NODE_IMAGE_NAME:$2" "$IMAGE_REGISTRY/$MARKET_IMAGE" $DEPLOYMENT_NAME \
-            || just deploy "$IMAGE_REGISTRY/$FOG_NODE_IMAGE_NAME:$2" "$IMAGE_REGISTRY/$MARKET_IMAGE" $DEPLOYMENT_NAME
-            #just deploy "$IMAGE_REGISTRY/$FOG_NODE_IMAGE_NAME:$2" "$IMAGE_REGISTRY/$MARKET_IMAGE" $DEPLOYMENT_NAME
+            just refresh "$IMAGE_REGISTRY/$COMMON_IMAGE_NAME:$2" "$IMAGE_REGISTRY/$COMMON_IMAGE_NAME$3" $DEPLOYMENT_NAME \
+            || just deploy "$IMAGE_REGISTRY/$COMMON_IMAGE_NAME:$2" "$IMAGE_REGISTRY/$COMMON_IMAGE_NAME:$3" $DEPLOYMENT_NAME
         fi
-        just tunnels --command="'just scenario \"$DEPLOYMENT_NAME-$2\" {{city_name_node_targets}}'"
+        just tunnels --command="'just scenario \"$DEPLOYMENT_NAME-$2-$3\" {{city_name_node_targets}}'"
     }
 
     echo "Deploying..."
@@ -199,7 +221,8 @@ scenarii +city_name_node_targets:
     parallel --tty --shuf \
         --joblog ./joblog \
         run_scenario {#} {} \
-        ::: $(echo ${FOG_NODE_IMAGE_TAGS[@]})
+        ::: $(echo ${FOG_NODE_IMAGE_TAGS[@]}) \
+        :::+ $(echo ${MARKET_IMAGE_TAGS[@]})
 
     for INDEX in $(seq 1 3); do
         parallel --tty --joblog ./joblog --retry-failed
@@ -299,18 +322,16 @@ build_required_images user:
     set -e
 
     read -ra tags <<<"$FOG_NODE_IMAGE_TAGS"
-
-    for (( i=0; i<${#tags[@]}; i++ )); do
-        tags[$i]="fog_node_${tags[$i]}"
-    done
+    read -ra market_tags <<<"$MARKET_IMAGE_TAGS"
 
     commands=(
-        "cd $MANAGER_PATH && nix develop .#manager -c just ghcr {{user}} $(echo ${tags[@]})"
+        "cd $MANAGER_PATH && nix develop .#manager -c just ghcr {{user}} $(echo ${tags[@]}) $(echo ${market_tags[@]})"
         "cd $IOT_EMULATION_PATH && nix develop .#iot_emulation -c just ghcr {{user}}"
         "cd $FUNCTIONS_PATH && nix develop .#openfaas-functions -c just ghcr_all {{user}}"
     )
 
-    parallel --will-cite --lb ::: "${commands[@]}"
+    parallel --will-cite --halt-on-error 2 {1} 2> /dev/null ::: "${commands[@]}"
+    echo -e "[{{file_name(justfile_directory())}}] all images uploaded \033[1;32mOK\033[0m"
 
 [private]
 docker_campaign user variation="valuation_rates" experiments_dotfile=".experiments.env"  single_experiment_dotenvfile=".env": (build_required_images user)
@@ -535,19 +556,27 @@ upload experiments_dotfile=".experiments.env" skip_vms="false":
     source {{experiments_dotfile}}
     set +o allexport
     city=$({{RUN}} master.py get-city)
-    vm_path=$(nix build --extra-experimental-features nix-command --extra-experimental-features flakes .#enosvm --print-out-paths --no-link --quiet)/nixos.qcow2
-    ([ "{{skip_vms}}" = "true" ] || rsync -cazp --inplace --stats --perms --chmod=u+rwx,g+rwx,o+rwx $vm_path $city.grid5000.fr:~/nixos.env.qcow2)&
+    if [ {{skip_vms}} != "true" ]; then
+      echo "Building VMs"
+      vm_path=$(nix build --extra-experimental-features nix-command --extra-experimental-features flakes .#enosvm --print-out-paths --no-link --quiet 2> /dev/null)/nixos.qcow2
+      (rsync -cazpq --inplace --stats --perms --chmod=u+rwx,g+rwx,o+rwx $vm_path $city.grid5000.fr:~/nixos.env.qcow2 \
+        && echo -e "[{{file_name(justfile_directory())}}] master VM uploaded \033[32mOK\033[0m")&
 
-    ([ "{{skip_vms}}" = "true" ] || bash -c "cd iso ; nix develop .#iso -c just upload $city")&
+      cd iso
+      (nix develop .#iso -c just upload $city 2> /dev/null \
+        && echo -e "[{{file_name(justfile_directory())}}] fog_node VM uploaded \033[32mOK\033[0m")&
+    else
+      echo "Not building VMs"
+    fi
 
-    ssh $city.grid5000.fr mkdir -p enosvm
+    ssh $city.grid5000.fr mkdir -p enosvm 2> /dev/null
 
-    echo "Copying whitelisted files for mouting inside the master VM"
-
-    parallel --will-cite rsync -cazp --inplace --stats --perms --chmod=u+rwx,g+rwx,o+rwx {} $city.grid5000.fr:~/enosvm/{} \
-        ::: *.py .env {{experiments_dotfile}} justfile pipelines/
+    parallel --will-cite rsync -cazpq --inplace --stats --perms --chmod=u+rwx,g+rwx,o+rwx {} $city.grid5000.fr:~/enosvm/{} 2> /dev/null \
+        ::: *.py .env {{experiments_dotfile}} justfile pipelines
+    echo -e "[{{file_name(justfile_directory())}}] config files uploaded \033[32mOK\033[0m"
 
     wait
+    echo -e "[{{file_name(justfile_directory())}}] all files rsynced \033[1;32mOK\033[0m"
 
 
 master_exec user name experiments_dotfile=".experiments.env" skip_vms="false":
@@ -585,15 +614,25 @@ master_exec user name experiments_dotfile=".experiments.env" skip_vms="false":
 
 master_refresh user name experiments_dotfile=".experiments.env" skip_rebuild="false":
     #!/usr/bin/env bash
-    set -e
     set -o allexport
     source {{experiments_dotfile}}
     set +o allexport
 
+    pids=()
     just upload {{experiments_dotfile}} "true"&
+    pids+=($!)
     ([ "{{skip_rebuild}}" = "true" ] || just build_required_images {{user}})&
-    wait
+    pids+=($!)
 
+    for pid in "${pids[@]}"; do
+      wait $pid
+      if [ $? -ne 0 ]; then
+        echo "A command errored"
+        exit 1
+      fi
+    done
+
+    set -e
     {{RUN}} master.py run-command-refresh
 
 master_docker_campaign variation="valuation_rates" experiments_dotfile=".experiments.env"  single_experiment_dotenvfile=".env":
